name: macOS
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: 
        cd Proj
        ./build_macos.sh
      
